config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root "pages#home"

  # get 'home', to: 'pages#home', as: :home
  get 'project', to: 'pages#project', as: :project


  # Questions
  get 'questions/:url', to: 'questions#show', as: :question
  resources :questions, only: [:index, :show]

  get 'quotidiens/:url', to: 'quotidiens#show', as: :quotidien
  resources :quotidiens, only: [:index, :show]

  get 'entendus/:url', to: 'entendus#show', as: :entendu
  resources :entendus, only: [:index, :show]

  # Contact Page
  resources :contacts, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha => true

  def headers
    {
      :subject => "Formulaire de Contact",
      :to => "trandgthanh@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/entendu.rb
class Entendu < ApplicationRecord
  has_many :liens
end

app/models/lien.rb
class Lien < ApplicationRecord
  belongs_to :question, optional: true
  belongs_to :quotidien, optional: true
  belongs_to :entendu, optional: true
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :body
  validates :name, :email, :body, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :liens
end

app/models/quotidien.rb
class Quotidien < ApplicationRecord
  has_many :liens
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Message non-envoyé.'
      render :new
    end
  end
end

app/controllers/entendus_controller.rb
class EntendusController < ApplicationController
  def index
    @entendus = Entendu.all
  end

  def show
    @entendu_url = params[:url]
    @entendu = Entendu.find_by(url: @entendu_url)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    if @message.valid?
      MessageMailer.contact_me(@message).deliver_now
      redirect_to new_message_url, notice: "Message reçu, merci !"
    else
      render :new, notice: "Il y a eu une erreur dans l'envoi de votre message, réessayez !"
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :body)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def enter
  end

  def home
    @questions = Question.all

    @quotidiens = Quotidien.all

    @entendus = Entendu.all
  end

  def project
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
  end

  def show
    @question_url = params[:url]
    @question = Question.find_by(url: @question_url)

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/entendus_helper.rb
module EntendusHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quotidiens_helper.rb
module QuotidiensHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%= favicon_link_tag %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%# unless current_page?(root_path) %>
      <%= render 'shared/navbar' %>
    <%# end %>

    <div class="page">
      <%= yield %>
    </div>

    <%# unless current_page?(root_path) %>
      <%= render 'shared/footer' %>
    <%# end %>
  </body>
</html>

app/views/pages/enter.html.erb
<div class="full-banner page">
  <div class="white-rectangle">
    <div class="upper-rectangle">
      <%= image_tag ("logo.png"), class: "medium-logo" %>
    </div>
    <div class="mid-rectangle">
      <h1 class="banner-title">Bienvenue</h1>
      <p class="banner-text">Ce site a été créé par une patiente atteinte d'un cancer du sein. Il ne présente en aucun cas des avis d'experts de la santé et ne prétend pas remplacer l'avis de votre médecin. Son seul but est de partager les questionnements et les réponses trouvées par cette jeune patiente en espérant qu'ils puissent également vous aider.</p>
    </div>
    <div class="lower-rectangle text-center">
      <%= link_to home_path do %>
        <div class="banner-signature text-center">
          <h2>J'ai compris donc je clique pour accéder au site</h2>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="part-one">
  <div class="home-illustration">
    <div class="page-upper-left dot-one">
      <div class="page-upper-left-text text-center">
        <div class="page-upper-left-text-item">
          <h1 class= "h-big">Et si, on pouvait enfin rechercher notre cancer sur Internet ?</h1>
        </div>
        <div class="page-upper-left-text-item">
          <p class="p-small">
          On m’avait dit de ne pas chercher sur Internet et à juste titre. Je me suis vite retrouvée confrontée à des témoignages déprimants ou débordée par la pléthore d’informations. Cependant, je reste persuadée qu’Internet est un trésor, plein de pépites et qu’on peut, avec un peu de recul, de recherches et de curiosité, y trouver les meilleures sources pour comprendre sa maladie, pour trouver de l’aide dans la gestion de son quotidien et pour se rendre compte qu’en fait, que nous ne sommes pas seuls.
          <br><br>
          Comprendre sa maladie, ses mécanismes, est le premier pas vers la guérison. La connaître permet de mieux la dompter. Au cours de mon traitement, j’ai pu rassembler une liste de liens, d’articles sur Internet, qui m’ont aidé à comprendre cette maladie qui m’avait envahie et, pour éviter que cette liste repose inutilement dans mon ordinateur, pourquoi pas la partager avec vous et espérer qu’elle puisse, peut-être, également vous aider.
          </p>
        </div>
      </div>
      <div class="butt-test">
        <%= link_to(project_path, class: "butt-pink") do %>
            <p>Comprendre mon projet</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="page-questions dot-two text-center">
  <div class="page-questions-title">
    <div class="page-questions-title-item-1">
      <p><strong>Les Questions sur la Maladie</strong></p>
    </div>
    <div class="page-questions-title-item-2">
      <h1>Cancer, biopsie, carcinome canalaire infiltrait, grade, stade, hormonale, triple négatif ... <br> Comprendre ma maladie.</h1>
    </div>
  </div>
  <div class="page-questions-cards text-center">
    <div class="page-questions-row text-center">
      <% @questions.sample(3).each do |q| %>
        <div class="page-questions-card-item">
          <div class="col-md-4 text-center">
            <div class="page-questions-card-body text-center">
              <%= image_tag "#{q.url}.png", class: "question-card-image" %>
              <div class="page-questions-card-description">
                <%= link_to question_path(q.url) do %>
                  <h3><%= q.title %></h3>
                <% end %>
                <p><%= q.description %> <strong><%= link_to "Lire l'article", question_path(q.url), class: "pink-link"  %></strong></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="butt-question">
    <%= link_to(questions_path, class: "butt-pink") do %>
      <p>Voir les autres articles</p>
    <% end %>
  </div>
</div>

<div class="page-questions dot-two snow text-center">
  <div class="page-questions-title">
    <div class="page-questions-title-item-1">
      <p><strong>La Vie au Quotidien</strong></p>
    </div>
    <div class="page-questions-title-item-2">
      <h1>Alimentation, activités physiques, cheveux ... <br> Comment ma vie au quotidien est-elle affectée ?</h1>
    </div>
  </div>
  <div class="page-questions-cards text-center">
    <div class="page-questions-row text-center">
      <% @quotidiens.sample(3).each do |q| %>
        <div class="page-questions-card-item">
          <div class="col-md-4 text-center">
            <div class="page-questions-card-body text-center">
              <%= image_tag "#{q.url}.png", class: "question-card-image" %>
              <div class="page-questions-card-description">
                <%= link_to quotidien_path(q.url) do %>
                  <h3><%= q.title %></h3>
                <% end %>
                <p><%= q.description %> <strong><%= link_to "Lire l'article", quotidien_path(q.url), class: "pink-link"  %></strong></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="butt-question">
    <%= link_to(quotidiens_path, class: "butt-pink") do %>
      <p>Voir les autres articles</p>
    <% end %>
  </div>
</div>

<div class="page-questions dot-two text-center">
  <div class="page-questions-title">
    <div class="page-questions-title-item-1">
      <p><strong>L'Esprit Guérit le Corps ?</strong></p>
    </div>
    <div class="page-questions-title-item-2">
      <h1>Comment communiquer avec nos proches ?</h1>
    </div>
  </div>
  <div class="page-questions-cards text-center">
    <div class="page-questions-row text-center">
      <% @entendus.sample(3).each do |q| %>
        <div class="page-questions-card-item">
          <div class="col-md-4 text-center">
            <div class="page-questions-card-body text-center">
              <%= image_tag "pinkpaint.png", class: "question-card-image" %>
              <div class="page-questions-card-description">
                <%= link_to entendu_path(q.url) do %>
                  <h3><%= q.title %></h3>
                <% end %>
                <p><%#= q.description %> <strong><%= link_to "Lire l'article", entendu_path(q.url), class: "pink-link"  %></strong></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="butt-question">
    <%= link_to(entendus_path, class: "butt-pink") do %>
      <p>Voir les autres articles</p>
    <% end %>
  </div>
</div>



<div class="supplement-info">
  <h2>Vous ne trouvez pas l'information que vous recherchez ?</h2>
  <div class="butt-test butt-supp">
    <%= link_to(root_path, class: "butt-pink") do %>
        <p>Laissez-moi un message</p>
    <% end %>
  </div>
</div>

app/views/pages/homebis.html.erb
<div class="page-upper">

    <div class="page-upper-left dot-one">
      <div class="page-upper-left-text">
        <div class="page-upper-left-text-item">
          <h1 class= "h-big">« Les résultats sont revenus et ils ne sont pas bons du tout. Il va falloir faire un traitement général. »</h1>
        </div>
        <div class="page-upper-left-text-item">
          <p class="p-small">Voilà comment la nouvelle était tombée, comment mon histoire avec le cancer a commencé. Et à ce moment-là, mon cerveau n’a pas voulu comprendre. Avant que ma gynéco m’explique, que j’allais devoir être traitée par chimiothérapie, par radiothérapie, avec une chirurgie. Et c’est à ce moment-là que mes larmes ont coulé.
          <br><br>
          Parce que je n’avais pas d’antécédents dans la famille, parce que je comprenais seulement vaguement ce qu’on me racontait. Mon moment de <em>solitude</em>.
          <br><br>
          On ne m’avait dit de ne pas chercher sur Internet car oui, je me suis vite retrouvée confrontée à des témoignages déprimants et débordée par la pléthore d’informations. Cependant, je reste persuadée qu’Internet est un trésor, débordant de pépites et qu’on peut, avec un peu de recul, de recherches et de curiosité, y trouver les meilleures sources pour comprendre sa maladie, pour trouver de l’aide dans la gestion de son quotidien et pour se rendre compte qu’en fait, que nous ne sommes pas seuls.
          <br><br>
          Comprendre sa maladie, ses mécanismes, est le premier pas vers la guérison. La connaître permet de mieux la dompter. Au cours de mon traitement, j’ai pu rassembler une liste de liens, d’articles sur Internet, qui m’ont aidé à comprendre cette maladie qui m’avait envahie et, pour éviter que cette liste repose inutilement dans mon ordinateur, pourquoi pas la partager avec vous et espérer qu’elle puisse, peut-être également, vous aider.
          </p>
        </div>
      </div>
      <div class="butt-test">
        <%= link_to(project_path, class: "butt-pink") do %>
            <p>Comprendre mon projet</p>
        <% end %>
      </div>
    </div>
    <div class="page-upper-right">
      <div class="half-page-illustration"></div>
    </div>
</div>

<div class="page-questions dot-two text-center">
  <div class="page-questions-title text-center">
    <div class="page-questions-title-item-1">
      <p><strong>Les Questions sur la Maladie</strong></p>
    </div>
    <div class="page-questions-title-item-2">
      <h1>Cancer, biopsie, carcinome canalaire infiltrait, grade, stade, hormonale, triple négatif ... <br> Comprendre ma maladie.</h1>
    </div>
  </div>
  <div class="page-questions-cards text-center">
    <div class="page-questions-row text-center">
      <% @questions.sample(3).each do |q| %>
        <div class="page-questions-card-item">
          <div class="col-md-4 text-center">
            <div class="page-questions-card-body text-center">
              <%= image_tag "#{q.url}.png", class: "question-card-image" %>
              <div class="page-questions-card-description">
                <%= link_to question_path(q.url) do %>
                  <h3><%= q.title %></h3>
                <% end %>
                <p><%= q.description %> <strong><%= link_to "Lire l'article", question_path(q.url), class: "pink-link"  %></strong></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="page-questions-link">
    <%= link_to questions_path do %>
      <p>Voir les autres articles</p>
    <% end %>
  </div>
</div>

<div class="page-quotidien">
  <div class="page-quotidien-right text-center">
    <div class="page-questions-title text-center">
      <div class="page-questions-title-item-1">
        <p><strong>Les Listes pour Aider Au Quotidien</strong></p>
      </div>
      <div class="page-quotidiens-title-item-2">
        <h1>Nourriture, sports ... Comment ma vie au quotidien est-elle affectée ?</h1>
      </div>
    </div>
    <div class="page-quotidiens-cards">
      <% @quotidiens.each do |q| %>
        <div class="page-quotidiens-cards-item">
          <div class="page-quotidiens-cards-text">
            <%= link_to quotidien_path(q.url) do %>
              <p class="quotidien-title"><%= q.title %></p>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="page-entendus-link">
      <%= link_to quotidiens_path do %>
        <p>Voir d'autres listes</p>
      <% end %>
    </div>
  </div>
</div>

<div class="page-entendu">
  <div class="page-entendu-left">
    <div class="page-questions-title text-center">
      <div class="page-entendus-title-item-1 text-center">
        <h1>Comment communiquer avec nos proches ?</h1>
      </div>
      <div class="page-entendus-link">
        <%= link_to entendus_path do %>
          <p>Voir d'autres histoires</p>
        <% end %>
      </div>
    </div>
  </div>
<!--   <div class="page-entendu-right">
    <div class="page-entendu-items">
      <%# @entendus.sample(3).each do |e| %>
        <%#= link_to entendus_path do  %>
<!           <div class="page-entendus-card round text-center" style="background-image: url(assets/circle<%#= rand(2) %>.jpg)"> -->
<!--           <div class="page-entendus-card round text-center">
  <!         <div class="page-entendus-card round text-center"> -->
            <!-- <div class="entendus-title"> -->
              <!-- <h4 class="cursive"><%#= e.title %></h4> -->
<!--             </div>
          </div> -->
        <%# end %>
      <%# end %>
<!--     </div> -->
<!--   </div>  -->




  <div class="page-questions-cards text-center">
    <div class="page-questions-row text-center">
      <% @entendus.sample(3).each do |e| %>
        <div class="page-questions-card-item">
          <div class="col-md-4 text-center">
            <div class="page-questions-card-body text-center">
              <%#= image_tag "#{e.url}.png", class: "question-card-image" %>
              <%= image_tag "pinkpaint.png", class: "question-card-image" %>
              <div class="page-questions-card-description" style="box-shadow: 0 1px 5px 0 rgba(0,0,0,0.07),0 1px 0 0 rgba(0,0,0,0.03); background-color: white;">
                <%= link_to question_path(e.url) do %>
                  <h3 style="padding: 10px;"><%= e.title %></h3>
                <% end %>
                <p><strong><%= link_to "Lire l'article", entendu_path(e.url), class: "pink-link"  %></strong></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

</div>

<div class="supplement-info">
  <h2>Vous ne trouvez pas l'information que vous recherchez ?</h2>
  <div class="butt-test butt-supp">
    <%= link_to(root_path, class: "butt-pink") do %>
        <p>Laissez-moi un message</p>
    <% end %>
  </div>
</div>

<!-- <div class="page-sources text-center">
  <h1>Quelques sources d'informations ...</h1>
  <div class="page-sources-logos">
    <div class="source-logo">
      <%#= link_to "https://curie.fr/" do %>
        <%#= image_tag("curie-logo.png") %>
      <%# end %>
    </div>
    <div class="source-logo">
      <%#= link_to "https://www.ligue-cancer.net/" do %>
        <%#= image_tag("laligue-logo.png") %>
      <%# end %>
    </div>
    <div class="source-logo">
      <%#= link_to "http://www.e-cancer.fr/" do %>
        <%#= image_tag("inca-logo.png") %>
      <%# end %>
    </div>
  </div>
</div> -->




<!-- QUOTIDIEN -->


<!-- <div class="page-quotidien">
  <div class="page-quotidien-right text-center">
    <div class="page-questions-title text-center">
      <div class="page-questions-title-item-1">
        <p><strong>Les Listes pour Aider Au Quotidien</strong></p>
      </div>
      <div class="page-quotidiens-title-item-2">
        <h1>Nourriture, sports ... Comment ma vie au quotidien est-elle affectée ?</h1>
      </div>
    </div>
    <div class="page-quotidiens-cards">
      <%# @quotidiens.each do |q| %>
        <div class="page-quotidiens-cards-item">
          <div class="page-quotidiens-cards-text">
            <%#= link_to quotidien_path(q.url) do %>
              <p class="quotidien-title"><%= q.title %></p>
            <%# end %>
          </div>
        </div>
      <%# end %>
    </div>
    <div class="page-entendus-link">
      <%#= link_to quotidiens_path do %>
        <p>Voir d'autres listes</p>
      <%# end %>
    </div>
  </div>
</div> -->

app/views/pages/project.html.erb
<div class="project-page">
  <div class="project-portrait text-center">
    <%= image_tag ("thanh-portrait-drawing.png"), class: "photo-portrait" %>
  </div>
  <div class="project-title text-center">
    <h1>Mon Histoire</h1>
  </div>
  <div class="project-story text-center">
    <p>Mon histoire avec le cancer a commencé en Mars 2017 lorsque j'ai été diagnostiquée d'un cancer du sein de type triple négatif et de grade III à l'age de 26 ans. Lorem ipsum dolor amet tumblr affogato taxidermy four loko, mlkshk copper mug fashion axe kickstarter 3 wolf moon listicle poke. Iceland pop-up chambray swag copper mug brunch keffiyeh tote bag. Dreamcatcher farm-to-table drinking vinegar pok pok master cleanse next level. YOLO letterpress kitsch, scenester edison bulb prism flexitarian godard seitan.</p>
  </div>
  <div class="project-title text-center">
    <h1>Mon Projet</h1>
  </div>
  <div class="project-description text-center">
    <div class="project-subdescription text-center">
      <div class="project-subtitle text-center">
        <h4>La naissance du projet</h4>
      </div>
      <p>Lorem ipsum dolor amet tumblr affogato taxidermy four loko, mlkshk copper mug fashion axe kickstarter 3 wolf moon listicle poke. Iceland pop-up chambray swag copper mug brunch keffiyeh tote bag. Dreamcatcher farm-to-table drinking vinegar pok pok master cleanse next level. YOLO letterpress kitsch, scenester edison bulb prism flexitarian godard seitan.</p>
    </div>
    <div class="project-subdescription text-center">
      <div class="project-subtitle text-center">
        <h4>La création du site</h4>
      </div>
      <p>Lorem ipsum dolor amet tumblr affogato taxidermy four loko, mlkshk copper mug fashion axe kickstarter 3 wolf moon listicle poke. Iceland pop-up chambray swag copper mug brunch keffiyeh tote bag. Dreamcatcher farm-to-table drinking vinegar pok pok master cleanse next level. YOLO letterpress kitsch, scenester edison bulb prism flexitarian godard seitan.</p>
    </div>
  </div>
  <div class="project-illustrations">
    <%= image_tag ("comment-lire-mes-examens-de-diagnostic.png"), class: "project-illustrations-photos" %>
    <%= image_tag ("est-ce-que-c-est-grave.png"), class: "project-illustrations-photos" %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer text-center">
  <div class="footer-left col-md-4 col-xs-12">
    <%= image_tag ("logo.png"), class: "small-logo" %>
    <p>Comprendre le cancer du sein est un site créé par une patiente actuellement en rémission de la maladie et ne prétend en aucun cas donner un avis médical ou remplacer l'avis d'un médecin. Il s'agit d'une collecte dans le but de partager les informations trouvées.
    <br><br>
    Ce volet de "Comprendre" est le 1er d'une série de recherches, qui tentera de comprendre et de partager les informations trouvées dans d'autres domaines choisis par l'auteur.
    </p>
  </div>
  <div class="footer-right col-md-8 col-xs-12">
    <div class="footer-right-items">
      <div class="footer-right-item">
        <%= link_to questions_path do %>
          <p>Maladie</p>
        <% end %>
      </div>
      <div class="footer-right-item">
        <%= link_to quotidiens_path do %>
          <p>Quotidien</p>
        <% end %>
      </div>
      <div class="footer-right-item">
        <%= link_to root_path do %>
          <p>Entendus</p>
        <% end %>
      </div>
      <div class="footer-right-item">
        <%= link_to root_path do %>
          <p>Projet</p>
        <% end %>
      </div>
      <div class="footer-right-item-contact">
        <%= mail_to "trandgthanh@gmail.com" do %>
          <p>Me Contacter</p>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="below-footer">
  <p>Développé avec <i class="fas fa-heart"></i> par STUDIO BÔLÊ</p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="navbar-left">
    <%= link_to root_path do %>
      <%= image_tag ("logo.png"), class: "navbar-logo" %>
    <% end %>
  </div>
  <div class="navbar-middle">
    <div class="navbar-middle-item">
      <%= link_to questions_path do %>
        <p>Maladie</p>
      <% end %>
    </div>
    <div class="navbar-middle-item">
      <%= link_to quotidiens_path do %>
        <p>Quotidien</p>
      <% end %>
    </div>
    <div class="navbar-middle-item">
      <%= link_to entendus_path do %>
        <p>Entendus</p>
      <% end %>
    </div>
    <div class="navbar-middle-item">
      <%= link_to project_path do %>
        <p>Projet</p>
      <% end %>
    </div>
  </div>
  <div class="navbar-right">
    <%= mail_to "trandgthanh@gmail.com" do %>
      <i class="fas fa-envelope"></i>
    <% end %>
  </div>
</div>

<div class="navbar-mobile">
  <div class="navbar-middle-mobile">
    <%= link_to root_path do %>
      <%= image_tag ("logo.png"), class: "navbar-logo" %>
    <% end %>
  </div>
  <div class="navbar-menu-mobile">
    <div class="navbar-mobile-item">
      <%= link_to questions_path do %>
        <p>Maladie</p>
      <% end %>
    </div>
    <div class="navbar-mobile-item">
      <%= link_to quotidiens_path do %>
        <p>Quotidien</p>
      <% end %>
    </div>
    <div class="navbar-mobile-item">
      <%= link_to entendus_path do %>
        <p>Entendus</p>
      <% end %>
    </div>
    <div class="navbar-mobile-item">
      <%= link_to project_path do %>
        <p>Projet</p>
      <% end %>
    </div>
    <div class="navbar-right">
      <%= mail_to "trandgthanh@gmail.com" do %>
        <i class="fas fa-envelope"></i>
      <% end %>
    </div>
  </div>
</div>